repos:
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        - id: flake8
          name: flake8
          additional_dependencies: ["flake8-bugbear==19.8.0"]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1  # Use the ref you want to point at
      hooks:
        - id: trailing-whitespace
        - id: requirements-txt-fixer
        - id: end-of-file-fixer
    - repo: https://github.com/pycqa/isort
      rev: 5.8.0
      hooks:
        - id: isort
          name: isort (python)
        - id: isort
          name: isort (cython)
          types: [cython]
        - id: isort
          name: isort (pyi)
          types: [pyi]
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.7  # Use the sha / tag you want to point at
      hooks:
          - id: autopep8
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
        - id: autoflake
          args:
            - --expand-star-imports
            - --ignore-init-module-imports
            - --in-place
            - --remove-all-unused-imports
            - --remove-duplicate-keys
            - --remove-unused-variables
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.26.0
      hooks:
        - id: pyupgrade
    #- repo: https://github.com/pre-commit/mirrors-pylint
    #  rev: v2.5.3
    #  hooks:
    #    - id: pylint
    #      name: pylint with optional checks
    #      args:
    #        - --rcfile=.pylintrc
    #        - --exit-zero
    #      verbose: true
    #      additional_dependencies: &pylint_deps
    #        - pylint-odoo==3.5.0
    #    - id: pylint
    #      name: pylint with mandatory checks
    #      args:
    #        - --rcfile=.pylintrc-mandatory
    #      additional_dependencies: *pylint_deps
